# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-08 13:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='author',
        ),
        migrations.RemoveField(
            model_name='imagepost',
            name='author',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='author',
        ),
        migrations.AlterField(
            model_name='imagepost',
            name='model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Post'),
        ),
    ]
