# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-30 00:55
from __future__ import unicode_literals

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20161025_1800'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('facebook', models.URLField()),
                ('googleplus', models.URLField()),
                ('twitter', models.URLField()),
                ('email', models.EmailField(max_length=254)),
                ('role', models.CharField(max_length=100)),
                ('site', models.URLField()),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('description', models.TextField()),
            ],
        ),
    ]
