# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-30 01:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20161029_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataentry',
            name='intrument',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='dataentry',
            name='movie',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='dataentry',
            name='title',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
