# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-30 02:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20161029_2244'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataentry',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 10, 30, 2, 7, 29, 998000, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dataentry',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 10, 30, 2, 7, 36, 392000, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
