# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-30 12:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20161029_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataentry',
            name='movie',
            field=models.URLField(blank=True, null=True),
        ),
    ]
