# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-11-19 13:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20161119_1049'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dataentry',
            old_name='intrument',
            new_name='instrument',
        ),
    ]
