# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-11-19 14:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20161119_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagedataentry',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
