# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-11-19 14:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_imagedataentry_filename'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagedataentry',
            name='image',
        ),
    ]
