# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-17 12:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_remove_imagedataentry_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='dataentry',
            options={'verbose_name': 'DataEntry', 'verbose_name_plural': 'DataEntries'},
        ),
        migrations.AlterModelOptions(
            name='imagedataentry',
            options={'verbose_name': 'ImageDataEntry', 'verbose_name_plural': 'ImageDataEntries'},
        ),
        migrations.AlterModelOptions(
            name='imagepost',
            options={'verbose_name': 'ImagePost', 'verbose_name_plural': 'ImagePosts'},
        ),
        migrations.AlterModelOptions(
            name='observatory',
            options={'verbose_name': 'Observatory', 'verbose_name_plural': 'Observatories'},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'verbose_name': 'SubCategory', 'verbose_name_plural': 'SubCategories'},
        ),
        migrations.AlterModelOptions(
            name='teammember',
            options={'verbose_name': 'TeamMember', 'verbose_name_plural': 'TeamMembers'},
        ),
    ]
