# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-05-09 17:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20161217_0954'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='lattes',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='orcid',
            field=models.URLField(blank=True, null=True),
        ),
    ]
